export enum ActionTypes {
    SUBSCRIBE_PUSH = "SUBSCRIBE_PUSH",
    UNSUBSCRIBE_PUSH = "UNSUBSCRIBE_PUSH",
    SUBSCRIBING_PUSH = "SUBSCRIBING_PUSH",
    PUSH_SUBSCRIBED_SUCCESSFULLY = "PUSH_SUBSCRIBED_SUCCESSFULLY",
    PUSH_SUBSCRIPTION_ERROR = "PUSH_SUBSCRIPTION_ERROR",
    PUSH_DISCONNECTED = "PUSH_DISCONNECTED"
}