export enum ActionTypes {
    SUBSCRIBE_PUSH = "SUBSCRIBE_PUSH",
    UNSUBSCRIBE_PUSH = "UNSUBSCRIBE_PUSH",
    SUBSCRIBING_PUSH = "SUBSCRIBING_PUSH",
    PUSH_SUBSCRIBED_SUCCESSFULLY = "PUSH_SUBSCRIBED_SUCCESSFULLY",
    PUSH_SUBSCRIPTION_ERROR = "PUSH_SUBSCRIPTION_ERROR",
    PUSH_DISCONNECTED = "PUSH_DISCONNECTED",

    SENSOR_STATUS_CHANGED = "SENSOR_STATUS_CHANGED",
    SENSOR_ERROR = "SENSOR_ERROR",
    ENGINE_STATUS_CHANGED = "ENGINE_STATUS_CHANGED",
    ACTIVITY_DETECTION = "ACTIVITY_DETECTION"
}