import { Action } from "redux";
import { Promise } from "es6-promise";

export enum ActionTypes {
     /** Push Notifications */
    SUBSCRIBE_PUSH = "SUBSCRIBE_PUSH",
    UNSUBSCRIBE_PUSH = "UNSUBSCRIBE_PUSH",
    SUBSCRIBING_PUSH = "SUBSCRIBING_PUSH",
    PUSH_SUBSCRIBED_SUCCESSFULLY = "PUSH_SUBSCRIBED_SUCCESSFULLY",
    PUSH_SUBSCRIPTION_ERROR = "PUSH_SUBSCRIPTION_ERROR",
    PUSH_DISCONNECTED = "PUSH_DISCONNECTED",
    PUSH_RECEIVED = "PUSH_RECEIVED",

    /** Sensors */
    TOGGLE_SENSOR = "TOGGLE_SENSOR",
    FETCH_SENSORS = "FETCH_SENSORS",
}

export enum AsyncStatus {
    PENDING,
    COMPLETED,
    ERROR
}